# frozen_string_literal: true

source 'https://rubygems.org'
ruby '~> <%= Natra::Versions.ruby_minor %>'

gem 'activerecord', '~> <%= Natra::Versions.activerecord %>'
gem 'bcrypt', '~> 3.1'
gem 'oj', '~> 3.17'
gem 'pg', '~> <%= Natra::Versions.pg %>'
gem 'puma', '~> 8.0'
gem 'rack-timeout', '~> 0.7'
gem 'rake', '~> 13.0'
<% if @redis -%>
gem 'redis', '~> <%= Natra::Versions.redis %>'
<% end -%>
gem 'require_all', '~> 3.0'
gem 'scout_apm', '~> 6.0'
gem 'sinatra', '~> 4.1'
gem 'sinatra-activerecord', '~> 2.0', require: 'sinatra/activerecord'

group :development, :test do
  gem 'pry'
  gem 'pry-byebug'
end

group :test do
  gem 'amazing_print'
  gem 'database_cleaner-active_record'
  gem 'factory_bot'
  gem 'faker'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov', require: false
end
